import Head from 'next/head'
import NavBar from '~/components/NavBar'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col w-full h-screen">
        <NavBar />
        <div className="flex flex-col items-center w-full mt-10 space-y-5">
          <span className="font-bold text-xl text-gray-200">
            Welcome to&nbsp;
            <span className="text-lg font-bold">
              Samp<span className="text-gray-400">Ag</span>uita
            </span>
          </span>
          <span className="font-black text-5xl">
            Your ChemLab Assistant
          </span>
        </div>
      </div>
    </>
  )
}
