import Head from 'next/head'

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-row items-center justify-center w-full h-screen">
        <div className="flex flex-col items-center w-full">
          <span className="font-bold text-xl">Welcome to Sampaguita</span>
        </div>
      </div>
    </div>
  )
}
